### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/pivumeter-pulseaudio#1]
* [ ] - figure out how to prevent 25-30% CPU usage 😬 
* [ ] - add some smoothing to VU output (user configurable)
* [ ] - tidy up hacky PHAT BEAT library and figure out how to make output devices pluggable (CLI option to choose class to load?)
* [ ] - make a deamon and bundle with a systemd unit
* [ ] - make pulse sink either audio detect (figure out which one is being used?) or user-configurable
* [ ] - make VU Meter optionally adaptive to output volume
* [ ] - make VU meter colours configurable
* [ ] - libfftw?? for full FFT output on Unicorn HAT and co?

**Comment by Gadgetoid** [comment]
CPU usage really is just a factor of how much stream data is being processed. I switched to `PA_STREAM_PEAK_DETECT`  and only process the samples received every 5ms (dropping any samples between) which cut CPU usage from ~30% to ~12% on a Pi 400. Could probably cut this more by locking the display output to 50-60 FPS and decoupling it from the audio stream processing.
